# Having a file like this allows you to override Makefile definitions
# for your own particular keymap

# needed for space cadet shift
COMMAND_ENABLE   = no  # Commands for debug and configuration

ifndef QUANTUM_DIR
	include ../../../../Makefile
endif
